# Generated by Django 4.0.4 on 2022-05-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rma.address'),
        ),
    ]
