# Generated by Django 4.0.4 on 2022-05-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0002_address_complement_alter_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_code', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=256)),
                ('customer_person', models.CharField(max_length=128)),
                ('technician', models.CharField(max_length=128)),
                ('reason', models.TextField(blank=True, null=True)),
                ('min_pickup_date', models.DateField()),
                ('pickup_date', models.DateField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rma.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rma.customer')),
            ],
        ),
    ]
