# Generated by Django 4.0.4 on 2022-05-07 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0003_productreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreturn',
            name='rma_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
