# Generated by Django 4.0.4 on 2022-05-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0004_alter_productreturn_rma_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
