# Generated by Django 4.0.4 on 2022-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0008_remove_productreturn_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
